import pandas as pd
import numpy as np
import h5py
import json
import os
import statsmodels.api as sm
from statsmodels.base import model
import time 
from logger_config import get_logger

logger = get_logger(__name__)




def read_annotations(
    logistic_regression_annotation_file, df
):
    annotations = pd.read_csv(logistic_regression_annotation_file, sep = "\t")

    # Convert stringified lists to lists. 
    # List of the following format (1 for each sample at that locus):
    # [Case/control boolean, group name, [group covariate1, covariate2, ...]]
    annotations["annotation"] = annotations["annotation"].apply(json.loads) 
    assert(all(annotations["ac_case"] + annotations["ac_control"] == annotations["annotation"].apply(len))) # Indeed 1 sample entry per carrier
    # Remove any sites with 0 carriers (should be none, but quirk with counting hets only vs non-refs...)
    annotations = annotations[annotations["annotation"].apply(len) > 0].reset_index(drop = True)

    # Next, explode to get one row per sample
    annotations_exploded = annotations.explode("annotation", ignore_index=True) # This also handles sites with 0 carriers

    # Now, extract relevant fields (is_case, group, covariates)
    annotations_exploded["is_case"] = annotations_exploded["annotation"].str.get(0).astype("boolean")
    annotations_exploded["group"] = annotations_exploded["annotation"].str.get(1)
    annotations_exploded["covariates"] = annotations_exploded["annotation"].str.get(2)

    # Attached needed information from df to extract residue positions 
    annotations_exploded["Variant ID"] = annotations_exploded["chr"] + '-' + annotations_exploded["pos"].astype(str) + '-' + annotations_exploded["ref"]  + '-' + annotations_exploded["alt"]
    merged = annotations_exploded.merge(df, on=["Variant ID", "ac_case", "ac_control"], how="inner")
    assert(len(merged) == (df["ac_case"].sum() + df["ac_control"].sum())) # Ensure everything makes it over

    return merged[["Variant ID", "aa_pos",
                   "ac_case", "ac_control", 
                   "is_case", "group", "covariates"]]

def format_vars_for_logistic_regression(annotations, pos_adjacency):
    '''
    Given the annotations dataframe (for a single protein), format the 
    response variable, n, and covariates for logistic regression on that position.
    '''
    # Response variable
    y = annotations["is_case"].astype(int).to_numpy()

    # n (inside neighborhood or not)
    n = np.array([pos_adjacency[i-1] for i in annotations["aa_pos"]])

    # Covariates matrix
    covariates = np.vstack(annotations["covariates"].to_numpy())

    return y, n, covariates

def run_logistic_regression_on_vars(y, n, covariates):    
    # Construct matrix
    X = pd.concat([pd.Series(n, name="n"), pd.DataFrame(covariates)], axis=1)
    X = sm.add_constant(X)
    # Consider null model without n (our neighborhood indicator)
    X_null = X.drop(columns=["n"])

    # Fit
    res_null = sm.Logit(y, X_null).fit(disp=0)

    # See if adding n back in improves fit (what we care about)
    _, p_value, _ = res_null.score_test(
        exog_extra=X["n"]
        )

    return p_value[0]



def run_logistic_regression(
    uniprot_id, df, n_res, n_sims, logistic_regression_annotation_file, adjacency_matrix
):
    '''
    Run logistic regression on the given df (slimmed to a single protein) 
    using the provided annotation file for covariates, over n_sim simulations.
    Premutations are generated by shuffling case/contrl labels within strata.
    '''
    # Read in annotation file and process
    annotations = read_annotations(logistic_regression_annotation_file, df)

    
    # Run on observed data
    pval_matrix = np.ones((1 + n_sims, n_res)) # For populating; first row is observed p-val, rest are from sims, transpose later
    for j, pos_adjacency in enumerate(adjacency_matrix):
        y, n, covariates = format_vars_for_logistic_regression(annotations, pos_adjacency)
        if len(set(n)) <= 1:
            logger.info(f"{uniprot_id}: Skipping position {j} due to no variation in n: all {set(n)}")
        else:
            p_value = run_logistic_regression_on_vars(y, n, covariates)
            pval_matrix[0, j] = p_value

    # Start permutations
    start = time.time()
    for i in range(n_sims):
        # Shuffle case/control labels within strata (group)
        annotations_permuted = annotations.copy()
        annotations_permuted["is_case"] = annotations_permuted.groupby("group")["is_case"].transform(np.random.permutation)

        # Validate correct shuffling
        orig = annotations.groupby('group')['is_case'].sum()
        perm = annotations_permuted.groupby('group')['is_case'].sum()
        assert (orig == perm).all()
        assert annotations['is_case'].sum() == annotations_permuted['is_case'].sum()

        # Now, consider each position 
        for j, pos_adjacency in enumerate(adjacency_matrix):
            y, n, covariates = format_vars_for_logistic_regression(annotations_permuted, pos_adjacency)
            if len(set(n)) <= 1:
                continue
            else:
                p_value = run_logistic_regression_on_vars(y, n, covariates)
                pval_matrix[i+1, j] = p_value
        if (i+1) % 100 == 0:
            logger.info(f"{uniprot_id}: Completed {i+1} / {n_sims} simulations for logistic regression. {int(time.time() - start)} seconds elapsed.")




    return pval_matrix.T
